import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import b from "../public/b.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blogzo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.con}>
        <div className={styles.img}>
          <Image src={b} />
        </div>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores
          quibusdam ullam recusandae possimus deserunt voluptas quis quisquam
          esse at delectus adipisci earum, voluptatem ipsa libero. Nesciunt sint
          vero labore maxime iure cumque libero omnis fuga reprehenderit, dicta
          aliquid, dolorum sunt, dolores alias in vel obcaecati commodi sed
          illum! Dolorem atque optio molestiae, earum unde enim ratione autem
          eveniet amet repudiandae!
        </p>
      </main>
    </div>
  );
}
